-- 코드를 입력하세요
SELECT ugb.TITLE,	ugb.BOARD_ID,	ugr.REPLY_ID,	ugr.WRITER_ID,	ugr.CONTENTS,	TO_CHAR(ugr.CREATED_DATE,'YYYY-MM-DD')
FROM USED_GOODS_REPLY ugr
LEFT JOIN USED_GOODS_BOARD ugb
ON ugr.BOARD_ID = ugb.BOARD_ID
WHERE ugb.CREATED_DATE BETWEEN TO_DATE('20221001','YYYYMMDD') AND TO_DATE('20221031','YYYYMMDD')
ORDER BY TO_CHAR(ugr.CREATED_DATE,'YYYY-MM-DD'),ugb.TITLE;